### ISSUE TITLE
Variable의 Scope은 최소한으로 유지합시다

### ISSUE THREAD

**Issue by f-lab-Digitz** [OliviaYiju/Study_C-PrimerPlus#1]
https://github.com/OliviaYiju/Study_C-PrimerPlus/blob/14319833c5880b66096de0351fbce877babed618/Chapter2/Exercise01.cpp#L10

Global로 변수를 선언하는 것은 가능한 지양하도록 합시다. 가능한한 최소로 접근하게 Variable을 선언하는 것이 더 좋아요.

**Comment by OliviaYiju** [comment]
확인했습니다!
