### ISSUE TITLE
소문자로 시작하는 camelCase를 씁니다.

### ISSUE THREAD

**Issue by f-lab-Digitz** [OliviaYiju/Study_C-PrimerPlus#10]
https://github.com/OliviaYiju/Study_C-PrimerPlus/blob/451f880e88c1cd74b5a18e74d4fb06035fd7efeb/Chapter4/Exercise05.cpp#L17C5-L17C53

**Comment by OliviaYiju** [comment]
구조체 변수명 선언은 소문자로 시작하는 camelCase
